### ISSUE TITLE
Allow tracks to be queued

### ISSUE THREAD

**Issue by m-allanson** [MadeByLoosers/noise-box#1]
At the moment the noise to play is represented by a single string in NBModel. When a user clicks on a noise in the client the string is changed to the noise's URL and the change event is picked up by any listening hosts.

Ideally we want some sort of track queue, or playlist.

Will need to work out how to keep multiple hosts in sync with each other.  Look into streaming audio straight from the server.  Shoutcast?  Or some other way?

**Comment by jedrichards** [comment]
Here are some possible approaches:
- Ascertain a track's duration in seconds, either by parsing its ID3 tags, or perhaps by digging out its bitrate and multiplying by its filesize. Once the server knows how long the track is it can just initiate moving onto the next track in the queue whether all the hosts have finished playing or not ...
- Attach events to the <audio> tag, as soon as at least one host reports that its finished playing a track then move all the hosts on whether they've finished or not.
- As Mike mentioned above perhaps each NoiseBox could have an associated [SHOUTcast](http://en.wikipedia.org/wiki/SHOUTcast) internet radio station. I think jPlayer will play a SHOUTcast stream, and there seems to be a fair bit on Google about using Node to broadcast such things. This might be a "phase 2 thing" though!

**Comment by m-allanson** [comment]
Another option would be for each host to request the next track from the queue once it's finished the current track.  This means the hosts could end up out of sync, but each track would always be played all the way through by every host.  

[Icecast](http://www.icecast.org/) may be an alternative to SHOUTcast if we go down that route.

**Comment by orangespaceman** [comment]
I don't know how you've decided to make it, my original plan was that there would only ever be a single host for each room. 

The idea being that when a new track is selected, the host is alerted immediately via websockets. It could then add it to its own internal queue, and pick the next track when the one before ends.

**Comment by m-allanson** [comment]
Currently it allows as many hosts as you like, any requests to play a track will be pushed out to every host.  If we can work out a decent way of sending sounds to all hosts there's no reason to limit it to one.  It might be useful if you want the same sounds playing in two different physical locations, just add a new host and noise-box will take care of the rest.

**Comment by orangespaceman** [comment]
Point taken.  You'd better get on with it then.

**Comment by jedrichards** [comment]
I think a key thing here is that the model in the Node server is the final authority in terms of what's actually happening. Host clients are dumb ... they're basically restricted to a) being told to play a track and b) possibly reporting back that they've finished playing a track.

It's totally possible that, inside of the model, each host has its own personal queue (as opposed to there being a master queue for all hosts) and each host works their way through it ... that's a possibly quite a good way to do it actually.

Although it would be pretty complicated I do like the idea of each NoiseBox exposing its own live audio stream (say on a URL like http://www.noisebox.com/host/mynoisebox/stream ... and then you just point the host client at the stream and let it play continuously. All hosts would presumably be in almost perfect sync ... pipe out synced music to every room in the party with people adjusting the play order and voting for tracks in realtime from their smartphones! That could be awesome!
