### ISSUE TITLE
Stats - list the track that is currently playing

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#11]

**Comment by jedrichards** [comment]
As discussed this will be hard to do since the server isn't maintaining an accurate model of tracks (only a historical list of tracks that have been added). Instead we should just have a simple feed, i.e.

```
"pete" added "seagulls"
"pete" added "seagulls"
"pete" added "seagulls"
"mike" removed "seagulls"
"mike" said "enough already!"
```

I'll make a new issue ...
