### ISSUE TITLE
Automated build and deployment

### ISSUE THREAD

**Issue by m-allanson** [MadeByLoosers/noise-box#2]
Should be able to run a script to build and deploy the project.  Script should lint, minify, combine files etc.   Look into suitable build tools.

**Comment by jedrichards** [comment]
Relevant links?

http://clock.co.uk/tech-blogs/deploying-nodejs-apps
http://www.carbonsilk.com/node/deploying-nodejs-apps/
http://howtonode.org/deploying-node-upstart-monit

**Comment by m-allanson** [comment]
Let's try using Grunt JS for this.

**Comment by jedrichards** [comment]
Agreed.

**Comment by m-allanson** [comment]
Commit 6045f2382f0e92d0419dfa07ea9f9819fdd98c3a does basic deployment tasks.  No tests as of yet.
