### ISSUE TITLE
Deploy task should display a link to the site on successful deployment

### ISSUE THREAD

**Issue by m-allanson** [MadeByLoosers/noise-box#26]
Show a link to the deployed server at the end of the grunt deploy task.

Until there's a URL, maybe use 'curl icanhazip.com' to display the server's IP address.

**Comment by jedrichards** [comment]
`$ dig +short myip.opendns.com @resolver1.opendns.com`

**Comment by jedrichards** [comment]
This is fluff, I banish it from our issues list.
