### ISSUE TITLE
Using a mobile device as a host that plays noise

### ISSUE THREAD

**Issue by jedrichards** [MadeByLoosers/noise-box#3]
From limited testing it looks like iOS/mobile Safari refuses to load new audio into an `<audio>` tag unless its been initiated by a user interaction (i.e. a user initiated click event) ... I'm not sure what the situation is on other mobile browsers.

**Comment by jedrichards** [comment]
Bit more info:

http://buildingwebapps.blogspot.co.uk/2012/04/state-of-html5-audio-in-mobile-safari.html

Maybe some approaches to making it work:

http://remysharp.com/2010/12/23/audio-sprites/

**Comment by jedrichards** [comment]
Another question is what happens when you hook up and leave an iPhone/smartphone based host long enough for it to turn the screen off and/or lock+sleep? Does that clobber the web pages ability to make it play audio?

**Comment by m-allanson** [comment]
iOS 6 will now play audio from an &lt;audio&gt; tag for us.  

Lock / sleep appears to stop any audio from playing.

**Comment by orangespaceman** [comment]
As good as we can get it on iOS, just need to test on Android
