### ISSUE TITLE
Stop file list being recreated every time a user views a noise box

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#32]
At the moment, the generation of the file list is happening in the user controller, and so runs every time a new user views a noise box:

```
fh.listFiles("./public/sfx",function (err,files) {
```

This could probably be moved to either when the app starts up, or when a new host is created. The result could be cached and then just accessed every time a new user is added.  

This could become especially important if we start to check tracks for file length.

**Comment by jedrichards** [comment]
Yeah, good thinking. I just found this npm package for recursively walking directories, could be useful?

https://github.com/coolaj86/node-walk

**Comment by orangespaceman** [comment]
Agreed, that library looks good. 

We should probably use something like this rather than my hacked together file system helper.

We should combine working in the new file system lister with moving it to a more logical place in the application, and working in some mp3 metadata detection for track lengths (see #7)...

**Comment by pxg** [comment]
The mp3 list is loaded when the server starts now. I've tested it with the mp3s from dropbox and it's working well.

The only issue is the list never reloads (unless node does). We should add a function to reload the list and call it periodically or when someone adds a new song.
