### ISSUE TITLE
Check noiseboxes are being destroyed

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#33]
On the linode server - http://178.79.132.61:7001/ - it states that there are currently three noiseboxes being hosted.  

Anyone hosting these?  

If not, they're not being destroyed when everyone (including the host) leaves...

**Comment by jedrichards** [comment]
I don't think there's anything in there to destroy noise boxes when there are no connected users. Perhaps one way to do it would be to refresh a timestamp every time there was activity on a noise box (track played, host added/removed, user added/removed etc.) and then do a pass with a `setTimeout` every few hours and delete any noise boxes with a timestamp sufficiently in the past ...

**Comment by jedrichards** [comment]
First attempt is here https://github.com/GuntLondon/noise-box/commit/77be948412453753d35e1461e7f5a694d1c40958
