### ISSUE TITLE
Sort websocket proxying

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#43]
Websockets work when you view the site directly via the IP address, but don't work when you view the site via the domain name...

**Comment by jedrichards** [comment]
This is an issue with the node-http-proxy reverse proxy on the production server. It needs looking at to make it handle web sockets properly.

**Comment by jedrichards** [comment]
Proper proxying of web sockets just hit the nginx trunk:

http://trac.nginx.org/nginx/changeset/5073/nginx

Could soon be time to ditch the node proxy ...

**Comment by orangespaceman** [comment]
Fixed in the node-http-proxy: as we are specifying callback functions it doesn't automatically upgrade websockets:
https://github.com/nodejitsu/node-http-proxy/pull/349
