### ISSUE TITLE
Visual note when people aren't connecting via websockets

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#48]
When users connect through an old browser or via 3G, socket.io falls back to long-polling. This is currently causing some errors (see #46) 

Even after these errors are fixed, connecting via long-polling makes client interactions slow to perform. So we should display a message saying the connection is slow, and could be improved by using a modern browser or connecting via wifi

**Comment by jedrichards** [comment]
:+1:
