### ISSUE TITLE
killing a host while a track is playing

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#49]
If you start a long track, there's no way to stop it.

One way to stop it could be to kill and restart the host, but in this case the 'track finished' event is never fired, so no new tracks are ever started.

We either need a way to stop tracks, and/or we need to deal with what happens if a/the host disappears before a track has finished playing.

Also unclear what'll happen to the play queue when there are multiple hosts - do they all report that tracks have finished?

**Comment by jedrichards** [comment]
Hmm, I'm not sure. I think that once you start to look really closely at all this stuff you realise there's a tonne of complexity and subtlety we haven't considered. I'd need a close look at the code and a hard think before I had anything useful to add here!

**Comment by orangespaceman** [comment]
There is something simple we could do about this... (Not allowing users to stop a track, but to gracefully handle everything if a host is closed)

If a host is closed, and if it's the only/last host for the room, we should empty the play queue and remove the track from the 'now playing' list.

In fact, we could potentially kill the entire room if the host leaves - kicking all users out onto the home page with a flash message saying the room was closed by the host.

**Comment by m-allanson** [comment]
Fixed with commit 5f2ee533d7
