### ISSUE TITLE
Solve node 0.10 / metadata parser issue

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#50]
With node 0.10, it is possible to see the home page, and also host a room. However, when viewing a room there seems to be with the metadata parser we're using - it worked fine with 0.8 but is infinite-looping now.

Errors are: "warning: possible EventEmitter memory leak detected. 11 listeners added."

And: "EMFILE, too many open files"

I started looking into it, looks like it's the way files are being opened to check the metadata. I dug into the library code a little, it could well be to do with the way they've changed how these file streams work internally in node 0.10: http://nodejs.org/api/stream.html#stream_compatibility

Another option could be to do with node opening too many files for the file system to cope with. If that is the problem, this lib could solve it: https://github.com/isaacs/node-graceful-fs

So for the moment I have disabled the metadata check in [/lib/sfx-metadata-parser.js](https://github.com/GuntLondon/noise-box/blob/dev/src/app/lib/sfx-metadata-parser.js#L24) - this at least means we can get the site running with node 0.10, the main downside is temporarily we can't see how long any tracks are.

**Comment by orangespaceman** [comment]
Sorted - changed the parser.on() methods to parser.once() methods in the [sfx-metadata-parser.js](https://github.com/GuntLondon/noise-box/blob/dev/src/app/lib/sfx-metadata-parser.js) file to stop them infinite looping

**Comment by jedrichards** [comment]
So changing from on() to once() ... is that fixing a problem with the way
the musicmetadata lib is interacting with the new Stream API in Node 0.10,
or is it just part of the proper way to be using the new stream stuff
generally?

**Comment by orangespaceman** [comment]
That's a good question.
