### ISSUE TITLE
Linting/testing and "use strict"

### ISSUE THREAD

**Issue by jedrichards** [MadeByLoosers/noise-box#6]
As far as I understand it only one "use strict" pragma needs to be defined in the main function that kicks everything off. As long as everything else happens within the scope of that main function the "use strict"ness will apply to all child function scopes.

So maybe wrap the stuff that kicks everything off in server.js in an immediately executed anonymous function with a "use strict" in it, and then we don't need to put it anywhere else?

The linting won't be smart enough to not complain the lack of "use strict" in the other files, so maybe turn off that option?

**Comment by m-allanson** [comment]
Just using 'use strict' once on the frontend now.
