### ISSUE TITLE
Add track length to the end of track names

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#7]
On the sfx track listing put the time of each sound effect in brackets next to its name

**Comment by orangespaceman** [comment]
https://github.com/leetreveil/node-musicmetadata is an easy to use npm library which allows access to certain track metadata but not track length / duration.

https://github.com/nikhilm/node-taglib might be a better option (but I couldn't get it to work)

Trying to avoid using libraries such as ffmpeg due to the overhead, but if we move the file system / track listing (see #32) then this could be less of an issue

**Comment by jedrichards** [comment]
Looks like bitrate is encoded into the binary MP3 header in the 4 bits from bit 17 to bit 20. We could try and parse it out ourselves?

http://mpgedit.org/mpgedit/mpeg_format/MP3Format.html

Bitrate x file size should give the duration ...

**Comment by orangespaceman** [comment]
Interesting idea!  Does this work with VBR as well as CBR mp3 files?  

I think we need to re-encode all of our files anyway, as they're in a variety of formats, many of which won't work with HTML5 &lt;audio&gt;.  We could probably script this re-encoding, and ensure that all outputted files are a standard bitrate. In fact, if we're going to do this, maybe we could add a duration header (or similar) if there is one.

Might be a problem when we then let people add their own tracks...

**Comment by jedrichards** [comment]
Yeah, if we're in control of the MP3s then we can make sure there's a `duration` ID3 tag in there, which would be simple to parse out with an existing library. If people can add any old mp3 from Dropbox or wherever, then it gets more complicated.

In my experience working with MP3s and ID3 tags in Flash `duration` is just about the rarest tag out there unfortunately!

Does HTML5 `<audio>` fire off any metadata or progress events we could tap into and avoid doing the work ourselves?

Also, there are JS audio player libraries we could maybe use on the client? Might simplify our audio playing code and expose metadata on the file being played?

http://www.jplayer.org/

**Comment by orangespaceman** [comment]
I think we should work in the option to display the duration ID3 tag alongside the track title if it is present, that way it doesn't matter if it isn't set.

Also we are currently using the filename rather than the ID3 title - we could switch it to use the title if set (and not empty) rather than the file name.

I believe you can get to some details via the &lt;audio&gt; - so we could get the duration of the currently played track etc, but it's not much help for the initial tracklist.

Agree on potentially using a third-party audio library for the host, I've just been thinking that it might be good to add in play/pause/skip functionality.

**Comment by orangespaceman** [comment]
While we're doing this also remove (or standardise) all other ID3 tags - artist, album etc - as these will all be quite random...

**Comment by jedrichards** [comment]
This is basically done! Well done Pete and me.
